services:
  api_gateway_nest:
    build: ./http-api-gateway-nest
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway-nest/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
    restart: always
  hello_nest_microservice:
    build: ./hello-nest-microservice
    volumes:
      - ./hello-nest-microservice/src:/usr/src/app/src
    command: yarn start:dev
  hello_rust_microservice:
    build: ./hello-rust-microservice
    volumes:
      - ./hello-rust-microservice:/app
    command: sh -c "cargo watch -x run"
  hello_python_microservice:
    build: ./hello-python-microservice
    volumes:
      - ./hello-python-microservice:/app
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- python src/main.py
  nats:
    image: nats
    ports:
      - 4222:4222